[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Ephemerides = "6a9c3322-c8fe-4c26-8ad6-14a6f8acd2a0"

[sources]
Ephemerides = {path = ".."}

[compat]
BenchmarkTools = "1"
julia = "1.7"
