
test_dir = artifact"testdata"
DJ2000 = 2451545.0

@testset "JSMD Interfaces" verbose=true begin

    path_de421 = joinpath(test_dir, "spk2_ex1.bsp")
    path_pa421 = joinpath(test_dir, "pa421.bpc")

    de421 = EphemerisProvider(path_de421)
    pa421 = jEphem.load(EphemerisProvider, path_pa421)

    kern = jEphem.load(EphemerisProvider, [path_pa421, path_de421])

    points = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 199, 299, 301, 399, 499]
    axes = [31006]

    # Test inexistent file error
    @test_throws SystemError EphemerisProvider("c3c12c.bsp")

    # Test EphemerisProvider printing
    @test repr(de421) == "1-kernel EphemerisProvider"
    @test repr(EphemerisProvider([path_de421, path_pa421])) == "2-kernel EphemerisProvider"

    io = IOBuffer();
    show(IOContext(io, :limit => false), "text/plain", de421)
    @test String(take!(io)) == "1-kernel EphemerisProvider:\n \"$path_de421\"\n"

    # Test comment retrieval
    ephj = EphemerisProvider(joinpath(test_dir, "spk20_ex1.bsp"))
    @test Ephemerides.comment(ephj.files[1]) == "Generated by Michele Ceresoli (michele.ceresoli@polimi.it) for Ephemerides.jl testing.\n\x04"

    # Test DAF routines
    @test Ephemerides.initial_record(ephj.files[1].header) == ephj.files[1].header.fwd
    @test Ephemerides.final_record(ephj.files[1].header) == ephj.files[1].header.bwd
    @test Ephemerides.free_address(ephj.files[1].header) == ephj.files[1].header.ffa
    @test Ephemerides.filename(ephj.files[1].header) == ephj.files[1].header.name

    @test Ephemerides.initial_record(ephj.files[1]) == Ephemerides.initial_record(ephj.files[1].header)
    @test Ephemerides.final_record(ephj.files[1]) == Ephemerides.final_record(ephj.files[1].header)
    @test Ephemerides.free_address(ephj.files[1]) == Ephemerides.free_address(ephj.files[1].header)

    # CALCEPH.jl files
    ephc = CalcephProvider(path_de421)
    epho = CalcephProvider(path_pa421)

    # Time properties tests
    @test jEphem.ephem_timescale(de421) == 1
    @test jEphem.ephem_timescale(pa421) == 1

    # FIXME: there is a .5 difference when using the PCK kernel in the timespan
    # for (ej, ec) in zip((de421, pa421), (ephc, epho))
    for (ej, ec) in zip((de421,), (ephc,))
        jt = jEphem.ephem_timespan(ej)
        jc = jEphem.ephem_timespan(ec)

        @test jt[1] - jc[1] == 0
        @test jt[2] - jc[2] == 0
        @test jt[3] - jc[3] == 0
    end

    @test jEphem.ephem_available_axes(de421) == Int64[]
    @test jEphem.ephem_available_points(pa421) == Int64[]

    @test sort(jEphem.ephem_available_axes(pa421)) == axes
    @test sort(jEphem.ephem_available_points(de421)) == points

    @test sort(jEphem.ephem_available_axes(kern)) == axes
    @test sort(jEphem.ephem_available_points(kern)) == points

    # Data records tests
    @test jEphem.ephem_position_records(pa421) == jEphem.EphemPointRecord[]
    @test jEphem.ephem_orient_records(de421) == jEphem.EphemAxesRecord[]

    prec = sort(jEphem.ephem_position_records(de421), by = x -> x.target, rev = true)
    crec = sort(jEphem.ephem_position_records(ephc), by = x -> x.target, rev = true)

    for (rec, recc) in zip(prec, crec)

        @test ((rec.center == recc.center && rec.target == recc.target) ||
               (rec.center == recc.target && rec.target == recc.center))

        @test rec.axes == recc.axes
        @test rec.jd_start == recc.jd_start
        @test rec.jd_stop == recc.jd_stop
    end

    orec = sort(jEphem.ephem_orient_records(pa421), by = x -> x.target, rev = true)
    corec = sort(jEphem.ephem_orient_records(epho), by = x -> x.target, rev = true)

    for (rec, recc) in zip(orec, corec)
        @test ((rec.target == recc.target && rec.axes == recc.axes) ||
               (rec.axes == recc.target && rec.target == recc.axes))

        @test rec.jd_start == recc.jd_start
        @test rec.jd_stop == recc.jd_stop
    end

    @testset "Prepared zero-allocation routes" begin
        point_record = only(filter(rec -> rec.center == 3 && rec.target == 301, prec))
        point_start = (point_record.jd_start - DJ2000) * 86400
        point_stop = (point_record.jd_stop - DJ2000) * 86400
        point_time = (point_start + point_stop) / 2

        direct = prepare_ephemeris(
            de421, 3, 301; timespan=(point_start, point_stop)
        )
        reverse_direct = prepare_ephemeris(
            de421, 301, 3; timespan=(point_start, point_stop)
        )

        for evaluator in (ephem_vector3, ephem_vector6, ephem_vector9, ephem_vector12)
            @test evaluator(direct, point_time) ==
                  evaluator(de421, 3, 301, point_time)
            @test evaluator(reverse_direct, point_time) ==
                  evaluator(de421, 301, 3, point_time)
            @test evaluator((direct, reverse_direct), point_time) == (
                evaluator(direct, point_time),
                evaluator(reverse_direct, point_time),
            )
        end
        @test D¹(t -> ephem_vector3(direct, t), point_time) ≈
              ephem_vector6(direct, point_time)[4:6] atol=1e-12 rtol=1e-12

        duplicate_points = EphemerisProvider([path_de421, path_de421])
        composite = prepare_ephemeris(duplicate_points, 3, 301)
        reverse_composite = prepare_ephemeris(duplicate_points, 301, 3)
        @test ephem_vector6(composite, point_time) ==
              ephem_vector6(duplicate_points, 3, 301, point_time)
        @test ephem_vector6(reverse_composite, point_time) ==
              ephem_vector6(duplicate_points, 301, 3, point_time)

        axes_record = only(orec)
        axes_start = (axes_record.jd_start - DJ2000) * 86400
        axes_stop = (axes_record.jd_stop - DJ2000) * 86400
        axes_time = (axes_start + axes_stop) / 2
        orientation = prepare_orientation(
            pa421, 1, 31006; timespan=(axes_start, axes_stop)
        )
        @test ephem_rotation6(orientation, axes_time) ==
              ephem_rotation6(pa421, 1, 31006, axes_time)

        duplicate_axes = EphemerisProvider([path_pa421, path_pa421])
        composite_orientation = prepare_orientation(duplicate_axes, 1, 31006)
        @test ephem_rotation6(composite_orientation, axes_time) ==
              ephem_rotation6(duplicate_axes, 1, 31006, axes_time)

        # Compile the paths before measuring steady-state allocations.
        ephem_vector3(de421, 3, 301, point_time)
        ephem_vector3(direct, point_time)
        ephem_vector3((direct, reverse_direct), point_time)
        ephem_vector3(composite, point_time)
        ephem_rotation3(orientation, axes_time)
        @test (@allocated ephem_vector3(de421, 3, 301, point_time)) == 0
        @test (@allocated ephem_vector3(direct, point_time)) == 0
        @test (@allocated ephem_vector3((direct, reverse_direct), point_time)) == 0
        @test (@allocated ephem_vector3(composite, point_time)) == 0
        @test (@allocated ephem_rotation3(orientation, axes_time)) == 0

        @test_throws ArgumentError prepare_ephemeris(
            de421, 3, 301; timespan=(point_stop, point_start)
        )
        @test_throws jEphem.EphemerisError ephem_vector3(direct, point_stop + 1)
    end

    yj1, yc1 = zeros(3), zeros(3)
    yj2, yc2 = zeros(6), zeros(6)
    yj3, yc3 = zeros(9), zeros(9)
    yj4, yc4 = zeros(12), zeros(12)

    # Point ephemeris tests
    @test_throws jEphem.EphemerisError jEphem.ephem_compute!(yj1, de421, 0.0, 0.0, 301, 399, 0)

    jEphem.ephem_compute!(yj1, de421, DJ2000, 0.0, 301, 3, 0)
    jEphem.ephem_compute!(yc1, ephc, DJ2000, 0.0, 301, 3, 0)

    jEphem.ephem_compute!(yj2, de421, DJ2000, 0.0, 301, 3, 1)
    jEphem.ephem_compute!(yc2, ephc, DJ2000, 0.0, 301, 3, 1)

    jEphem.ephem_compute!(yj3, de421, DJ2000, 0.0, 301, 3, 2)
    jEphem.ephem_compute!(yc3, ephc, DJ2000, 0.0, 301, 3, 2)

    jEphem.ephem_compute!(yj4, de421, DJ2000, 0.0, 301, 3, 3)
    jEphem.ephem_compute!(yc4, ephc, DJ2000, 0.0, 301, 3, 3)

    @test yc1 ≈ yj1 atol=1e-11 rtol=1e-11
    @test yc2 ≈ yj2 atol=1e-11 rtol=1e-11
    @test yc3 ≈ yj3 atol=1e-11 rtol=1e-11
    @test yc4 ≈ yj4 atol=1e-11 rtol=1e-11

    # Axes ephemeris tests
    @test_throws jEphem.EphemerisError jEphem.ephem_orient!(yj1, pa421, 0.0, 0.0, 301, 1, 0)

    jEphem.ephem_orient!(yj1, pa421, DJ2000, 0.0, 31006, 1, 0)
    jEphem.ephem_orient!(yc1, epho, DJ2000, 0.0, 31006, 1, 0)

    jEphem.ephem_orient!(yj2, pa421, DJ2000, 0.0, 31006, 1, 1)
    jEphem.ephem_orient!(yc2, epho, DJ2000, 0.0, 31006, 1, 1)

    jEphem.ephem_orient!(yj3, pa421, DJ2000, 0.0, 31006, 1, 2)
    jEphem.ephem_orient!(yc3, epho, DJ2000, 0.0, 31006, 1, 2)

    jEphem.ephem_orient!(yj4, pa421, DJ2000, 0.0, 31006, 1, 3)
    jEphem.ephem_orient!(yc4, epho, DJ2000, 0.0, 31006, 1, 3)

    @test yc1 ≈ yj1 atol=1e-11 rtol=1e-11
    @test yc2 ≈ yj2 atol=1e-11 rtol=1e-11
    @test yc3 ≈ yj3 atol=1e-11 rtol=1e-11
    @test yc4 ≈ yj4 atol=1e-11 rtol=1e-11

end;
